model_name,strategy_args,model_params,mae,mse,rmse,mape,smape,mase,wape,msmape,mae_norm,mse_norm,rmse_norm,mape_norm,smape_norm,mase_norm,wape_norm,msmape_norm,file_name,fit_time,inference_time,actual_data,inference_data,log_info
RegressionModel,"{""num_rollings"": 48000, ""pred_len"": 96, ""strategy_name"": ""rolling_forecast"", ""stride"": 1, ""train_test_split"": 0.8}","{""lags"": 96, ""normalization"": true}",,,,,,,,,,,,,,,,,,,,,,"Traceback (most recent call last):
  File ""/home/OTB_revised/ts_benchmark/evaluation/strategy/rolling_forecast.py"", line 107, in execute
    model.forecast_fit(train_valid_data, SPLIT_DICT.get(series_name, self.strategy_config[""train_valid_split""]))
  File ""/home/OTB_revised/ts_benchmark/baselines/darts/darts_models.py"", line 132, in forecast_fit
    return self.model.fit(train_data, val_series=valid_data)
  File ""/opt/conda/envs/OTB/lib/python3.8/site-packages/darts/models/forecasting/regression_model.py"", line 722, in fit
    self._fit_model(
  File ""/opt/conda/envs/OTB/lib/python3.8/site-packages/darts/models/forecasting/regression_model.py"", line 544, in _fit_model
    self.model.fit(training_samples, training_labels, **kwargs)
  File ""/opt/conda/envs/OTB/lib/python3.8/site-packages/sklearn/base.py"", line 1152, in wrapper
    return fit_method(estimator, *args, **kwargs)
TypeError: fit() got an unexpected keyword argument 'val_series'

fit() got an unexpected keyword argument 'val_series'"
